services:
  # myrargb:
  #   build:
  #     context: .
  #     dockerfile: ./docker/Dockerfile
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - FLASK_ENV=production
  #     - CHROME_URL=http://browser:4444
  #     - LOGGER_LEVEL=ERROR
  #     - HTTP_PROXY=http://172.17.0.1:10808
  #     - HTTPS_PROXY=http://172.17.0.1:10808
  #     - NVIDIA_VISIBLE_DEVICES=all
  #   volumes:
  #     - ./data:/app/data
  #   runtime: nvidia
  #
  # browser:
  #   image: selenium/standalone-chrome:latest
  #   ports:
  #     - "4444:4444"
  #   shm_size: "2g"
      

  kafka:
    image: apache/kafka:4.3.0-rc1
    hostname: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9200:9200"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      TZ: Asia/Shanghai


  kafka-ui:
    image: provectuslabs/kafka-ui
    ports:
      - "9090:8080"
    depends_on:
      - kafka
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:9092
      - TZ=Asia/Shanghai

