services:
  myrargb:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - CHROME_URL=http://browser:4444
      - LOGGER_LEVEL=ERROR
      - HTTP_PROXY=http://172.17.0.1:10808
      - HTTPS_PROXY=http://172.17.0.1:10808
      

  # browser:
  #   image: selenium/standalone-chrome:latest
  #   ports:
  #     - "4444:4444"
  #   shm_size: "2g"
      
